// Reimplement definitions from <kernel-root>/include/uapi/linux/dpll.h

package dpll

const DPLL_MCGRP_MONITOR = "monitor"
const (
	DPLL_A_TYPES = iota
	DPLL_A_ID
	DPLL_A_MODULE_NAME
	DPLL_A_CLOCK_ID
	DPLL_A_MODE
	DPLL_A_MODE_SUPPORTED
	DPLL_A_LOCK_STATUS
	DPLL_A_TEMP
	DPLL_A_TYPE
	DPLL_A_PIN_ID
	DPLL_A_PIN_BOARD_LABEL
	DPLL_A_PIN_PANEL_LABEL
	DPLL_A_PIN_PACKAGE_LABEL
	DPLL_A_PIN_TYPE
	DPLL_A_PIN_DIRECTION
	DPLL_A_PIN_FREQUENCY
	DPLL_A_PIN_FREQUENCY_SUPPORTED
	DPLL_A_PIN_FREQUENCY_MIN
	DPLL_A_PIN_FREQUENCY_MAX
	DPLL_A_PIN_PRIO
	DPLL_A_PIN_STATE
	DPLL_A_PIN_DPLL_CAPS
	DPLL_A_PIN_PARENT

	__DPLL_A_MAX
	DPLL_A_MAX = __DPLL_A_MAX - 1
)

const (
	DPLL_CMDS = iota
	DPLL_CMD_DEVICE_ID_GET
	DPLL_CMD_DEVICE_GET
	DPLL_CMD_DEVICE_SET
	DPLL_CMD_DEVICE_CREATE_NTF
	DPLL_CMD_DEVICE_DELETE_NTF
	DPLL_CMD_DEVICE_CHANGE_NTF
	DPLL_CMD_PIN_ID_GET
	DPLL_CMD_PIN_GET
	DPLL_CMD_PIN_SET
	DPLL_CMD_PIN_CREATE_NTF
	DPLL_CMD_PIN_DELETE_NTF
	DPLL_CMD_PIN_CHANGE_NTF

	__DPLL_CMD_MAX
	DPLL_CMD_MAX = (__DPLL_CMD_MAX - 1)
)
